apiVersion: config.linkerd.io/v1alpha1
kind: LinkerdConfig
metadata:
  name: edge-19.12.3
spec:
  global:
    clusterDomain: cluster.local
    cniEnabled: false
    configMap: linkerd-config
    identityContext:
      trustDomain: cluster.local
      trustAnchorsPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBgjCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
        eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjAwMTAyMDYwNjAxWhcNMjEwMTAx
        MDYwNjIxWjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
        YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQdddzpXPQRsC5EpbcGw0KDZDzk
        OTODqMqPDeT2oZj1ioaCosF4JQpeNVeL7HqVGJBGpNAQI+z2GP9NDF+o1nDuo0Iw
        QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
        MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDRwAwRAIgUiL4/o9/cBmA7tkc
        FQdu1/mUG364kc9gJh6SGJqgdSgCIHTcnK4xilrxpuPeRpwPn5Got1Ra2kv+CU9E
        Pxzf/r/A
        -----END CERTIFICATE-----
      issuanceLifeTime: 86400s
      clockSkewAllowance: 20s
      scheme: linkerd.io/tls
    linkerdNamespace: linkerd
    omitWebhookSideEffects: true
    version: edge-19.12.3
  proxy:
    adminPort: 4191
    controlPort: 4190
    disableExternalProfiles: true
    ignoreInboundPorts: ["8888","9999"]
    ignoreOutboundPorts: ["8888","9999"]
    inboundPort: 4143
    logLevel: warn,linkerd2_proxy=info
    outboundPort: 4140
    proxyImage:
      name: gcr.io/linkerd-io/proxy
      pullPolicy: IfNotPresent
    proxyInitImage:
      name: gcr.io/linkerd-io/proxy-init
      pullPolicy: IfNotPresent
    proxyInitImageVersion: v1.2.0
    proxyVersion: edge-19.12.3
    proxyUID: 2102
    resource:
      limits:
        cpu: "1"
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 20Mi
